# Generated by Django 2.1.5 on 2019-04-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190410_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newevent',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=100)),
                ('e_location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='result/')),
                ('desc1', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newnotice',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('desc1', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newresult',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='result/')),
                ('desc1', models.TextField(max_length=500)),
            ],
        ),
    ]
