# Generated by Django 2.1.5 on 2019-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190415_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newfeedback',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cls1', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('msg1', models.TextField(max_length=500)),
                ('reply', models.TextField(max_length=500)),
            ],
        ),
    ]
