# Generated by Django 2.1.5 on 2019-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_newfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
